// macOS Tahoe stock app configuration
// type: 'core' means a dedicated functional component; 'stub' means a placeholder window.

export const stockApps = [
  {
    id: 'finder',
    name: 'Finder',
    type: 'core',
    color: '#007AFF',
    iconFace: 'finder',
  },
  {
    id: 'launchpad',
    name: 'Launchpad',
    type: 'stub',
    color: '#7A7A7A',
    iconFace: 'rocket',
  },
  {
    id: 'safari',
    name: 'Safari',
    type: 'core',
    color: '#34C759',
    iconFace: 'compass',
  },
  {
    id: 'messages',
    name: 'Messages',
    type: 'stub',
    color: '#34C759',
    iconFace: 'chat',
  },
  {
    id: 'mail',
    name: 'Mail',
    type: 'core',
    color: '#007AFF',
    iconFace: 'envelope',
  },
  {
    id: 'maps',
    name: 'Maps',
    type: 'core',
    color: '#34C759',
    iconFace: 'map',
  },
  {
    id: 'photos',
    name: 'Photos',
    type: 'core',
    color: '#FF9500',
    iconFace: 'photos',
  },
  {
    id: 'calendar',
    name: 'Calendar',
    type: 'core',
    color: '#FF3B30',
    iconFace: 'calendar',
  },
  {
    id: 'contacts',
    name: 'Contacts',
    type: 'stub',
    color: '#FFCC00',
    iconFace: 'person',
  },
  {
    id: 'reminders',
    name: 'Reminders',
    type: 'stub',
    color: '#FF9500',
    iconFace: 'check',
  },
  {
    id: 'notes',
    name: 'Notes',
    type: 'core',
    color: '#FFCC00',
    iconFace: 'note',
  },
  {
    id: 'music',
    name: 'Music',
    type: 'stub',
    color: '#FF3B30',
    iconFace: 'music',
  },
  {
    id: 'tv',
    name: 'TV',
    type: 'stub',
    color: '#1C1C1E',
    iconFace: 'tv',
  },
  {
    id: 'podcasts',
    name: 'Podcasts',
    type: 'stub',
    color: '#AF52DE',
    iconFace: 'podcast',
  },
  {
    id: 'appstore',
    name: 'App Store',
    type: 'stub',
    color: '#007AFF',
    iconFace: 'bag',
  },
  {
    id: 'settings',
    name: 'System Settings',
    type: 'core',
    color: '#8E8E93',
    iconFace: 'gear',
  },
  {
    id: 'calculator',
    name: 'Calculator',
    type: 'core',
    color: '#FF3B30',
    iconFace: 'calculator',
  },
  {
    id: 'terminal',
    name: 'Terminal',
    type: 'core',
    color: '#1C1C1E',
    iconFace: 'terminal',
  },
  {
    id: 'facetime',
    name: 'FaceTime',
    type: 'stub',
    color: '#34C759',
    iconFace: 'video',
  },
  {
    id: 'news',
    name: 'News',
    type: 'stub',
    color: '#FF3B30',
    iconFace: 'newspaper',
  },
  {
    id: 'stocks',
    name: 'Stocks',
    type: 'stub',
    color: '#1C1C1E',
    iconFace: 'chart',
  },
  {
    id: 'books',
    name: 'Books',
    type: 'stub',
    color: '#FF9500',
    iconFace: 'book',
  },
  {
    id: 'home',
    name: 'Home',
    type: 'stub',
    color: '#FF9500',
    iconFace: 'home',
  },
  {
    id: 'weather',
    name: 'Weather',
    type: 'stub',
    color: '#007AFF',
    iconFace: 'cloud',
  },
  {
    id: 'clock',
    name: 'Clock',
    type: 'stub',
    color: '#1C1C1E',
    iconFace: 'clock',
  },
  {
    id: 'wallet',
    name: 'Wallet',
    type: 'stub',
    color: '#1C1C1E',
    iconFace: 'wallet',
  },
  {
    id: 'findmy',
    name: 'Find My',
    type: 'stub',
    color: '#34C759',
    iconFace: 'radar',
  },
  {
    id: 'phone',
    name: 'Phone',
    type: 'stub',
    color: '#34C759',
    iconFace: 'phone',
  },
  {
    id: 'journal',
    name: 'Journal',
    type: 'stub',
    color: '#FF9500',
    iconFace: 'journal',
  },
  {
    id: 'games',
    name: 'Games',
    type: 'stub',
    color: '#007AFF',
    iconFace: 'gamepad',
  },
  {
    id: 'freeform',
    name: 'Freeform',
    type: 'stub',
    color: '#FFCC00',
    iconFace: 'scribble',
  },
  {
    id: 'gamecenter',
    name: 'Game Center',
    type: 'stub',
    color: '#007AFF',
    iconFace: 'gamecenter',
  },
  {
    id: 'voicememos',
    name: 'Voice Memos',
    type: 'stub',
    color: '#FF3B30',
    iconFace: 'waveform',
  },
  {
    id: 'magnifier',
    name: 'Magnifier',
    type: 'stub',
    color: '#FF9500',
    iconFace: 'magnifier',
  },
  {
    id: 'trash',
    name: 'Trash',
    type: 'stub',
    color: '#8E8E93',
    iconFace: 'trash',
  },
];

export const coreAppIds = stockApps.filter(a => a.type === 'core').map(a => a.id);
export const stubAppIds = stockApps.filter(a => a.type === 'stub').map(a => a.id);

export function getAppById(id) {
  return stockApps.find((a) => a.id === id);
}
