import type { Stock } from './types'

export const stocks: Stock[] = [
  {
    id: 'stk-aapl',
    symbol: 'AAPL',
    name: 'Apple Inc.',
    price: 214.5,
    change: 2.34,
    changePercent: 1.1,
    marketCap: '3.3T',
    chartColor: 'bg-tahoe-green',
  },
  {
    id: 'stk-msft',
    symbol: 'MSFT',
    name: 'Microsoft Corporation',
    price: 425.8,
    change: -1.2,
    changePercent: -0.28,
    marketCap: '3.2T',
    chartColor: 'bg-tahoe-red',
  },
  {
    id: 'stk-googl',
    symbol: 'GOOGL',
    name: 'Alphabet Inc.',
    price: 176.2,
    change: 0.85,
    changePercent: 0.48,
    marketCap: '2.2T',
    chartColor: 'bg-tahoe-green',
  },
  {
    id: 'stk-amzn',
    symbol: 'AMZN',
    name: 'Amazon.com Inc.',
    price: 198.4,
    change: 3.1,
    changePercent: 1.59,
    marketCap: '2.1T',
    chartColor: 'bg-tahoe-green',
  },
  {
    id: 'stk-tsla',
    symbol: 'TSLA',
    name: 'Tesla, Inc.',
    price: 248.5,
    change: -4.5,
    changePercent: -1.78,
    marketCap: '790B',
    chartColor: 'bg-tahoe-red',
  },
  {
    id: 'stk-nvda',
    symbol: 'NVDA',
    name: 'NVIDIA Corporation',
    price: 132.6,
    change: 5.2,
    changePercent: 4.08,
    marketCap: '3.2T',
    chartColor: 'bg-tahoe-green',
  },
]
