const $ = (s, root = document) => root.querySelector(s);
const $$ = (s, root = document) => [...root.querySelectorAll(s)];
const windows = $('#windows');
let zIndex = 10;
let notes = [{title:'Welcome to Notes', body:'Ideas, lists, and thoughts all in one place.\n\nStart writing here...'}, {title:'Trip planning', body:'Book train tickets\nFind a place for dinner\nPack camera'}];
let currentNote = 0;

const apps = {
  Finder: {icon:'⌁', cls:'finder-app'}, Safari:{icon:'◉', cls:'safari-app'}, Mail:{icon:'✉', cls:'mail-app'}, Messages:{icon:'⌁', cls:'messages-app'}, Calendar:{icon:'5', cls:'calendar-app'}, Notes:{icon:'≡', cls:'notes-app'}, Photos:{icon:'✿', cls:'photos-app'}, 'System Settings':{icon:'⚙', cls:'settings-app'}, Terminal:{icon:'›_', cls:'terminal-app'}
};

function appIcon(name, extra='') { const a=apps[name]||{icon:'□',cls:''}; return `<span class="mini-icon ${a.cls} ${extra}">${a.icon}</span>`; }
function windowMarkup(name) {
  const content = {
    Finder: `<div class="finder-layout"><nav class="sidebar"><label>Favorites</label><button class="selected">⌁ <span>Recents</span></button><button>⌂ <span>Applications</span></button><button>▣ <span>Desktop</span></button><button>↓ <span>Downloads</span></button><label>iCloud</label><button>☁ <span>iCloud Drive</span></button><button>▣ <span>Shared</span></button><label>Locations</label><button>▰ <span>Macintosh HD</span></button></nav><div class="finder-main"><div class="toolbar"><button>‹</button><button>›</button><strong>Recents</strong><span></span><button>▦</button><button>⌕</button></div><div class="file-grid">${['Applications','Desktop','Documents','Downloads','Movies','Music','Pictures','Public'].map((x,i)=>`<button class="file-tile">${i===0?'<span class="big-folder blue-folder">▣</span>':'<span class="big-folder">▣</span>'}<b>${x}</b><small>Folder</small></button>`).join('')}</div></div></div>`,
    Safari: `<div class="safari-layout"><div class="browser-toolbar"><button>‹</button><button>›</button><button>↻</button><div class="address">⌕ <span>apple.com</span><small>⌄</small></div><button>☷</button><button>＋</button></div><div class="browser-tabs"><span class="tab active">Apple</span><span class="tab">Start Page</span><button>＋</button></div><div class="safari-page"><div class="apple-word">Apple</div><h1>Welcome to the<br/><em>new</em> era.</h1><p>Explore the latest Apple innovations.</p><button class="page-button">Learn more <span>›</span></button><div class="page-orb"></div></div></div>`,
    Mail: `<div class="mail-layout"><nav class="mail-sidebar"><button class="compose">✎ <span>Compose</span></button><label>Mailboxes</label><button class="selected">▣ <span>Inbox</span><b>3</b></button><button>★ <span>VIP</span></button><button>◷ <span>Drafts</span></button><button>↗ <span>Sent</span></button><button>⌫ <span>Trash</span></button></nav><div class="mail-list"><div class="list-title">Inbox <button>•••</button></div>${['Your Apple receipt','The weather this week','Design inspiration','Welcome to iCloud'].map((x,i)=>`<button class="mail-row ${i===0?'unread':''}"><span class="sender">${['Apple','Weather','Are.na','iCloud'][i]}</span><span>${x}</span><small>${i===0?'Today':'Yesterday'}</small></button>`).join('')}</div><article class="mail-message"><span class="mail-avatar">A</span><h2>Your Apple receipt</h2><small>Apple &lt;no_reply@apple.com&gt; · Today, 9:41 AM</small><hr/><p>Thanks for your purchase.</p><p>Your receipt is ready to view in your Apple Account. No action is needed.</p><button class="blue-button">View Receipt</button></article></div>`,
    Messages: `<div class="messages-layout"><nav class="conversation-list"><div class="message-header">Messages <button>✎</button></div><div class="message-search">⌕ Search</div>${['Alex Morgan','Work Group','Mum','Apple Support'].map((x,i)=>`<button class="conversation ${i===0?'active':''}">${appIcon('Messages','avatar')}<span><b>${x}</b><small>${['That sounds perfect! See you then.','You: I sent the files over','Photo','Your Apple ID was used'][i]}</small></span><time>${i<2?'10:0'+i:'Mon'}</time></button>`).join('')}</nav><section class="chat"><header>${appIcon('Messages','avatar')}<strong>Alex Morgan<small>iMessage</small></strong><button>ⓘ</button></header><div class="chat-body"><div class="bubble theirs">Hey! Are we still on for lunch today?</div><div class="bubble mine">Absolutely. I know a great place nearby.</div><div class="bubble theirs">That sounds perfect! See you then.</div></div><div class="chat-input"><button>＋</button><input placeholder="iMessage"/><button>☻</button><button>↑</button></div></section></div>`,
    Calendar: `<div class="calendar-layout"><nav class="calendar-sidebar"><button class="new-event">＋ <span>New Event</span></button><div class="mini-cal"><b>August 2026</b><div class="weekdays">S M T W T F S</div><div class="mini-days">${Array.from({length:31},(_,i)=>`<span class="${i===4?'today':''}">${i+1}</span>`).join('')}</div></div><label>Calendars</label><button>● Work</button><button>● Personal</button></nav><section class="month-view"><div class="calendar-toolbar"><button>‹</button><button>›</button><strong>August 2026</strong><span></span><button>Today</button><button>Month⌄</button></div><div class="calendar-grid"><div class="calendar-week-head">${['SUN','MON','TUE','WED','THU','FRI','SAT'].map(x=>`<b>${x}</b>`).join('')}</div><div class="days-grid">${Array.from({length:35},(_,i)=>{let n=i-5;return `<div class="day-cell">${n>0&&n<32?`<span class="day-number ${n===5?'today':''}">${n}</span>${n===5?'<div class="event blue-event">Lunch with Alex</div>':''}${n===12?'<div class="event red-event">Team sync</div>':''}`:''}</div>`}).join('')}</div></div></section></div>`,
    Notes: `<div class="notes-layout"><nav class="notes-list"><div class="notes-actions"><button>＋</button><button>▱</button></div><div class="note-search">⌕ Search</div>${notes.map((n,i)=>`<button class="note-row ${i===currentNote?'selected':''}" data-note="${i}"><b>${n.title}</b><small>Today</small><span>${n.body.split('\n')[0]}</span></button>`).join('')}</nav><article class="note-editor"><input id="note-title" value="${notes[currentNote].title}" /><textarea id="note-body">${notes[currentNote].body}</textarea><button class="note-share">□</button></article></div>`,
    Photos: `<div class="photos-layout"><nav class="photos-sidebar"><button class="selected">▦ <span>Library</span></button><button>♡ <span>For You</span></button><button>▣ <span>Albums</span></button><button>✿ <span>Memories</span></button><label>Shared Albums</label><button>☁ <span>Shared with You</span></button></nav><section class="photo-main"><div class="toolbar"><strong>Library</strong><span></span><button>⊞</button><button>＋</button></div><h1>All Photos</h1><div class="photo-grid">${Array.from({length:24},(_,i)=>`<button class="photo photo-${i+1}" aria-label="Photo ${i+1}"></button>`).join('')}</div></section></div>`,
    'System Settings': `<div class="settings-layout"><nav class="settings-sidebar"><div class="settings-profile"><span class="profile-avatar">M</span><span><b>Mike</b><small>Apple Account</small></span></div><div class="settings-search">⌕ Search</div>${['General','Appearance','Accessibility','Control Center','Siri & Spotlight','Desktop & Dock','Displays','Wallpaper','Notifications','Sound','Focus','Privacy & Security'].map((x,i)=>`<button class="settings-item ${i===0?'selected':''}"><span>${['⚙','◐','◎','◒','✦','▥','▤','▧','▰','◖','◴','▣'][i]}</span>${x}</button>`).join('')}</nav><section class="settings-main"><h1>General</h1><div class="settings-section"><button><span>ⓘ</span><b>About</b><small>›</small></button><button><span>↻</span><b>Software Update</b><small>macOS is up to date ›</small></button><button><span>▤</span><b>Storage</b><small>221.4 GB of 994.7 GB used ›</small></button></div><h2>Transfer or Reset</h2><div class="settings-section"><button><span>⇄</span><b>Transfer or Reset</b><small>›</small></button></div></section></div>`,
    Terminal: `<div class="terminal-layout"><div class="terminal-output">Last login: Wed Aug  5 09:42:21 on ttys001<br/><br/><span class="green">mike@MacBook-Pro</span> <span class="purple">~</span> % <span id="terminal-command"></span><br/><br/>Welcome to zsh<br/>To update your shell, run <span class="blue">chsh -s /bin/zsh</span><br/><span class="green">mike@MacBook-Pro</span> <span class="purple">~</span> % <input id="terminal-input" autofocus /></div></div>`
  }[name] || '<div class="empty-app">This app is not available in the demo.</div>';
  return `<div class="window app-window" data-app="${name}" style="z-index:${++zIndex}"><header class="window-titlebar"><div class="traffic"><button class="close">×</button><button class="minimize">−</button><button class="maximize">+</button></div><strong>${appIcon(name)} ${name}</strong><div class="window-spacer"></div></header><div class="window-content">${content}</div></div>`;
}

function openApp(name){
  let win = $(`.app-window[data-app="${name}"]`);
  if(win){win.classList.remove('minimized'); win.style.zIndex=++zIndex; return;}
  windows.insertAdjacentHTML('beforeend',windowMarkup(name));
  win = $(`.app-window[data-app="${name}"]`); positionWindow(win,name); bindWindow(win); 
}
function positionWindow(win,name){ const sizes={Finder:[780,530],Safari:[870,570],Mail:[900,570],Messages:[760,560],Calendar:[900,590],Notes:[760,560],Photos:[880,590],'System Settings':[900,620],Terminal:[720,430]}; const [w,h]=sizes[name]||[700,500]; win.style.width=`min(${w}px, calc(100vw - 40px))`;win.style.height=`min(${h}px, calc(100vh - 110px))`;win.style.left=`max(20px,calc(50% - ${w/2}px))`;win.style.top=`max(45px,calc(50% - ${h/2+10}px))`;}
function bindWindow(win){
  win.addEventListener('mousedown',()=>win.style.zIndex=++zIndex);
  $('.close',win).onclick=()=>win.remove(); $('.minimize',win).onclick=()=>win.classList.add('minimized'); $('.maximize',win).onclick=()=>win.classList.toggle('maximized');
  $$('.note-row',win).forEach(b=>b.onclick=()=>{currentNote=+b.dataset.note; win.outerHTML=windowMarkup('Notes'); const nw=$('.app-window[data-app="Notes"]'); positionWindow(nw,'Notes');bindWindow(nw)});
  const title=$('#note-title',win), body=$('#note-body',win); if(title){title.oninput=()=>notes[currentNote].title=title.value; body.oninput=()=>notes[currentNote].body=body.value}
  const terminal=$('#terminal-input',win); if(terminal) terminal.onkeydown=e=>{if(e.key==='Enter'){const value=terminal.value; $('#terminal-command',win).textContent=value; terminal.value=''; if(value==='clear')$('.terminal-output',win).innerHTML=''; else $('.terminal-output',win).insertAdjacentHTML('beforeend',`<br/>${value==='help'?'Available commands: help, date, whoami, clear':value==='whoami'?'mike':`zsh: command not found: ${value}`}<br/><span class="green">mike@MacBook-Pro</span> <span class="purple">~</span> % <input id="terminal-input" autofocus />`); bindWindow(win)}};
}

const menus={apple:['About This Mac','System Settings…','App Store…','Recent Items ›','Sleep','Restart…','Shut Down…','Lock Screen','Log Out Mike…'],finder:['About Finder','Preferences…','Empty Trash…','Services ›','Hide Finder','Quit Finder'],file:['New Finder Window','New Folder','Open','Get Info','Move to Trash','Eject'],edit:['Undo','Redo','Cut','Copy','Paste','Select All'],view:['as Icons','as List','as Columns','as Gallery','Show Preview','Show View Options'],go:['Back','Forward','Enclosing Folder','Computer','AirDrop','Home','Downloads','Network'],window:['Minimize','Zoom','Cycle Through Windows','Show Previous Tab','Bring All to Front'],help:['macOS Help','Get Started','Keyboard Shortcuts','What’s New in macOS']};
function showMenu(type,button){$('.context-menu').remove();const m=document.createElement('div');m.className='context-menu';m.innerHTML=(menus[type]||[]).map((x,i)=>`<button data-menu-item="${i}">${x}</button>`).join('');const r=button.getBoundingClientRect();m.style.left=`${r.left}px`;m.style.top=`${r.bottom+3}px`;document.body.appendChild(m);m.onclick=e=>{if(e.target.dataset.menuItem==='1'&&type==='apple')openApp('System Settings');if(e.target.textContent.includes('New Finder'))openApp('Finder');m.remove()};}

function closeOverlays(){ $$('.overlay,.control-center,.context-menu').forEach(x=>x.classList.add('hidden')); }
document.addEventListener('click',e=>{
  const open=e.target.closest('[data-open]'); if(open){openApp(open.dataset.open);closeOverlays();return}
  const menu=e.target.closest('[data-menu]'); if(menu){showMenu(menu.dataset.menu,menu);return}
  if(e.target.closest('#control-btn')){$('#control-center').classList.toggle('hidden');return}
  if(e.target.closest('#spotlight-btn')){$('#spotlight').classList.remove('hidden');$('#spotlight-input').focus();return}
  if(e.target.closest('.close-overlay')){$('#'+e.target.dataset.close).classList.add('hidden');return}
  if(e.target.closest('[data-action="trash"]')){showContext(e.clientX,e.clientY,['Open Trash','Empty Trash…']);return}
  if(e.target.closest('[data-action="launchpad"]')){$('#launchpad').classList.remove('hidden');$('#launch-search').focus();return}
  if(!e.target.closest('.context-menu')&&!e.target.closest('.menubar'))$('.context-menu')?.remove();
});
function showContext(x,y,items){const m=$('#context-menu');m.innerHTML=items.map((x,i)=>`<button>${x}</button>`).join('');m.style.left=x+'px';m.style.top=y+'px';m.classList.remove('hidden')}
document.addEventListener('contextmenu',e=>{if(e.target.closest('#desktop')){e.preventDefault();showContext(e.clientX,e.clientY,['New Folder','Get Info','Change Wallpaper…','Sort By ›']);}});
$('#spotlight-input').oninput=e=>{const q=e.target.value.toLowerCase();$('#spotlight-results').innerHTML=q?Object.keys(apps).filter(x=>x.toLowerCase().includes(q)).map(x=>`<button class="result" data-open="${x}">${appIcon(x)} <span>${x}</span></button>`).join(''):''};
$('#launch-search').oninput=e=>$$('.launch-item').forEach(x=>x.style.display=x.textContent.toLowerCase().includes(e.target.value.toLowerCase())?'flex':'none');
function fillLaunchpad(){ $('#launch-grid').innerHTML=Object.keys(apps).map(x=>`<button class="launch-item" data-open="${x}">${appIcon(x)}<span>${x}</span></button>`).join('')+`<button class="launch-item"><span class="mini-icon launch-icon">▦</span><span>Other</span></button>`; }
fillLaunchpad();
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeOverlays();if(e.metaKey&&e.key===' '){e.preventDefault();$('#spotlight').classList.remove('hidden');$('#spotlight-input').focus()}if(e.key==='F4'){$('#launchpad').classList.remove('hidden')}});
function updateClock(){const d=new Date(); const day=d.toLocaleDateString('en-GB',{weekday:'short',month:'short',day:'numeric'});const time=d.toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'});$('#clock').textContent=`${day}  ${time}`};updateClock();setInterval(updateClock,1000);
// A small initial state makes the desktop feel lived in while keeping windows easy to dismiss.
openApp('Finder');
