const $ = (s, p = document) => p.querySelector(s);
const $$ = (s, p = document) => [...p.querySelectorAll(s)];
const desktop = $('#desktop');
const layer = $('#window-layer');
let topZ = 20;
let activeApp = 'Finder';
let activeMenu = null;
const state = { volume: 62, playing: false, brightness: 82, stage: false };

const appMeta = {
  finder: ['Finder', '◕'], safari: ['Safari', '⌁'], messages: ['Messages', '●'], mail: ['Mail', '✉'], maps: ['Maps', '⌖'],
  photos: ['Photos', '✿'], facetime: ['FaceTime', '▰'], calendar: ['Calendar', '6'], notes: ['Notes', '≡'], music: ['Music', '♫'],
  settings: ['System Settings', '⚙'], downloads: ['Downloads', '↓'], trash: ['Trash', '♲']
};

const menus = {
  'apple-menu': [['About This Mac', 'about'], ['sep'], ['System Settings…', 'open:settings'], ['App Store…', 'toast:App Store is up to date'], ['sep'], ['Recent Items', 'submenu'], ['sep'], ['Force Quit…', 'force', '⌥⌘⎋'], ['sep'], ['Sleep', 'sleep'], ['Restart…', 'toast:Restart is disabled in this web demo'], ['Shut Down…', 'toast:Shut Down is disabled in this web demo'], ['sep'], ['Lock Screen', 'lock', '⌃⌘Q'], ['Log Out Demo User…', 'toast:You’re already exploring as Demo User']],
  'app-menu': [['About Finder', 'aboutapp'], ['sep'], ['Settings…', 'open:settings', '⌘,'], ['sep'], ['Services', 'submenu'], ['sep'], ['Hide Finder', 'hide', '⌘H'], ['Hide Others', 'hideothers', '⌥⌘H'], ['Show All', 'showall'], ['sep'], ['Quit Finder', 'quit', '⌘Q']],
  'file-menu': [['New Finder Window', 'open:finder', '⌘N'], ['New Folder', 'newfolder', '⇧⌘N'], ['Open', 'toast:Select an item to open', '⌘O'], ['Open With', 'submenu'], ['sep'], ['Close Window', 'closeactive', '⌘W'], ['Get Info', 'toast:No item selected', '⌘I'], ['Rename', 'toast:No item selected'], ['sep'], ['Move to Trash', 'toast:No item selected', '⌘⌫']],
  'edit-menu': [['Undo', 'toast:Nothing to undo', '⌘Z'], ['Redo', 'toast:Nothing to redo', '⇧⌘Z'], ['sep'], ['Cut', 'clipboard:cut', '⌘X'], ['Copy', 'clipboard:copy', '⌘C'], ['Paste', 'clipboard:paste', '⌘V'], ['Select All', 'selectall', '⌘A'], ['sep'], ['Emoji & Symbols', 'emoji', '⌃⌘Space']],
  'view-menu': [['as Icons', 'view:icons', '⌘1'], ['as List', 'view:list', '⌘2'], ['as Columns', 'view:columns', '⌘3'], ['sep'], ['Show Sidebar', 'toast:Sidebar is already visible', '⌥⌘S'], ['Show Preview', 'toast:Preview toggled', '⇧⌘P'], ['sep'], ['Enter Full Screen', 'fullscreen', '⌃⌘F']],
  'go-menu': [['Back', 'toast:No previous location', '⌘['], ['Forward', 'toast:No next location', '⌘]'], ['Enclosing Folder', 'open:finder', '⌘↑'], ['sep'], ['Recents', 'open:finder', '⇧⌘F'], ['Documents', 'open:finder', '⇧⌘O'], ['Desktop', 'open:finder', '⇧⌘D'], ['Downloads', 'open:downloads', '⌥⌘L'], ['sep'], ['Connect to Server…', 'toast:Server browser opened', '⌘K']],
  'window-menu': [['Minimize', 'minactive', '⌘M'], ['Zoom', 'zoomactive'], ['Move & Resize', 'submenu'], ['sep'], ['Bring All to Front', 'front'], ['sep'], ['Show Previous Tab', 'toast:No other tabs'], ['Show Next Tab', 'toast:No other tabs']],
  'help-menu': [['Tahoe Help', 'help'], ['Tips for Your Mac', 'toast:Tip: press ⌘ Space to open Spotlight'], ['sep'], ['Keyboard Shortcuts', 'shortcuts']]
};

function updateClock(){
  const d = new Date();
  $('#menu-time').textContent = d.toLocaleTimeString([], {hour:'numeric',minute:'2-digit'});
  $('#menu-date').textContent = d.toLocaleDateString([], {weekday:'short',month:'short',day:'numeric'});
  $('#widget-day').textContent = d.toLocaleDateString([], {weekday:'long'}).toUpperCase();
  $('#widget-date').textContent = d.getDate(); $('#dock-date').textContent = d.getDate();
}
updateClock(); setInterval(updateClock, 1000);

function toast(message){const el=$('#toast');el.textContent=message;el.classList.remove('hidden');clearTimeout(el._timer);el._timer=setTimeout(()=>el.classList.add('hidden'),2200)}
function closePanels(except){['#menu-popover','#control-center','#notification-center','#spotlight'].forEach(id=>{if(id!==except)$(id).classList.add('hidden')});$$('.menu-trigger').forEach(x=>x.classList.remove('selected'));activeMenu=null}

function showMenu(button){
  const id=button.dataset.menu; const pop=$('#menu-popover');
  if(activeMenu===id&&!pop.classList.contains('hidden')){closePanels();return}
  closePanels('#menu-popover'); activeMenu=id; button.classList.add('selected');
  let items=menus[id]||menus['app-menu'];
  if(id==='app-menu') items=items.map((x,i)=>i===0?[`About ${activeApp}`,'aboutapp']:i===2?[`${activeApp} Settings…`,'open:settings','⌘,']:i===6?[`Hide ${activeApp}`,'hide','⌘H']:i===10?[`Quit ${activeApp}`,'quit','⌘Q']:x);
  pop.innerHTML=items.map(item=>item[0]==='sep'?'<div class="menu-separator"></div>':`<div class="menu-item" data-action="${item[1]||''}"><span>${item[0]}</span>${item[1]==='submenu'?'<span class="submenu-arrow">›</span>':`<kbd>${item[2]||''}</kbd>`}</div>`).join('');
  pop.style.left=`${button.getBoundingClientRect().left}px`;pop.classList.remove('hidden');
}
$$('.menu-trigger').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();showMenu(b)}));
$('#menu-popover').addEventListener('click',e=>{const item=e.target.closest('.menu-item');if(item)performAction(item.dataset.action)});

function performAction(action){closePanels();if(!action)return;if(action.startsWith('open:'))return openApp(action.split(':')[1]);if(action.startsWith('toast:'))return toast(action.slice(6));
  const active=$('.window.focused');
  ({about:()=>openAbout(),aboutapp:()=>toast(`${activeApp} — designed for the Tahoe web desktop`),force:()=>toast('All applications are responding'),sleep:()=>{desktop.classList.add('sleeping');setTimeout(()=>desktop.classList.remove('sleeping'),800)},lock:()=>showLock(),hide:()=>active?.classList.add('hidden'),hideothers:()=>$$('.window:not(.focused)').forEach(w=>w.classList.add('hidden')),showall:()=>$$('.window').forEach(w=>w.classList.remove('hidden')),quit:()=>active&&closeWindow(active),closeactive:()=>active&&closeWindow(active),minactive:()=>active&&minimizeWindow(active),zoomactive:()=>active&&active.classList.toggle('maximized'),front:()=>active&&focusWindow(active),newfolder:()=>addFolder(),selectall:()=>$$('.file').forEach(f=>f.style.background='rgba(20,125,230,.18)'),fullscreen:()=>active&&active.classList.toggle('maximized'),help:()=>openHelp(),shortcuts:()=>toast('⌘ Space Spotlight · ⌘ W Close · ⌘ M Minimize'),emoji:()=>toast('😀  🌊  ✨  🏔️  💻'),clipboard:()=>toast('Clipboard action complete'),view:()=>toast('View updated')}[action]||(()=>toast('Done')))();
}

function focusWindow(win){$$('.window').forEach(w=>w.classList.remove('focused'));win.classList.add('focused');win.style.zIndex=++topZ;const id=win.dataset.app;activeApp=(appMeta[id]||[win.dataset.title])[0];$('.active-app-name').textContent=activeApp}
function closeWindow(win){const id=win.dataset.app;win.remove();if(!$$(`.window[data-app="${id}"]`).length)$(`.dock-icon[data-open="${id}"]`)?.classList.remove('running');const last=$$('.window').pop();if(last)focusWindow(last);else{$('.active-app-name').textContent='Finder';activeApp='Finder'}}
function minimizeWindow(win){win.classList.add('minimizing');setTimeout(()=>win.classList.add('hidden'),310);setTimeout(()=>win.classList.remove('minimizing'),350)}
function makeDraggable(win,bar){let sx,sy,sl,st,drag=false;bar.addEventListener('pointerdown',e=>{if(e.target.closest('button')||win.classList.contains('maximized'))return;drag=true;sx=e.clientX;sy=e.clientY;sl=win.offsetLeft;st=win.offsetTop;bar.setPointerCapture(e.pointerId)});bar.addEventListener('pointermove',e=>{if(!drag)return;win.style.left=Math.max(0,sl+e.clientX-sx)+'px';win.style.top=Math.max(0,st+e.clientY-sy)+'px'});bar.addEventListener('pointerup',()=>drag=false)}

function windowHTML(id,title,body,opts={}){const win=document.createElement('article');win.className='window';win.dataset.app=id;win.dataset.title=title;const n=$$('.window').length;win.style.width=(opts.width||760)+'px';win.style.height=(opts.height||500)+'px';win.style.left=(opts.left??Math.max(20,(innerWidth-(opts.width||760))/2+n*24))+'px';win.style.top=(opts.top??Math.max(12,(innerHeight-(opts.height||500))/2-25+n*18))+'px';win.innerHTML=`<header class="titlebar"><div class="traffic"><button class="close">Close</button><button class="minimize">Minimize</button><button class="zoom">Zoom</button></div><span class="window-title">${title}</span><div class="toolbar-actions">${opts.toolbar||''}</div></header><div class="window-body">${body}</div>`;layer.append(win);makeDraggable(win,$('.titlebar',win));$('.close',win).onclick=()=>closeWindow(win);$('.minimize',win).onclick=()=>minimizeWindow(win);$('.zoom',win).onclick=()=>win.classList.toggle('maximized');win.addEventListener('pointerdown',()=>focusWindow(win));focusWindow(win);return win}

function openApp(id){closePanels();const minimized=$(`.window[data-app="${id}"].hidden`);if(minimized){minimized.classList.remove('hidden');focusWindow(minimized);return}const existing=$(`.window[data-app="${id}"]`);if(existing&&id!=='finder'){focusWindow(existing);return}const meta=appMeta[id]||[id,id];let win;
  switch(id){
    case'finder':win=openFinder();break;case'safari':win=openSafari();break;case'messages':win=openMessages();break;case'mail':win=openMail();break;case'maps':win=openMaps();break;case'photos':win=openPhotos();break;case'facetime':win=openFaceTime();break;case'calendar':win=openCalendar();break;case'notes':win=openNotes();break;case'music':win=openMusic();break;case'settings':win=openSettings();break;case'downloads':win=openFinder('Downloads');break;case'trash':win=openTrash();break;
  }$(`.dock-icon[data-open="${id}"]`)?.classList.add('running');return win
}

function openFinder(section='Recents'){return windowHTML('finder',section,`<div class="finder-layout"><aside class="sidebar"><h4>Favorites</h4>${['AirDrop','Recents','Applications','Desktop','Documents','Downloads'].map(x=>`<div class="side-item ${x===section?'active':''}" data-place="${x}"><span>${x==='AirDrop'?'◉':'▰'}</span>${x}</div>`).join('')}<h4>iCloud</h4><div class="side-item"><span>☁</span>iCloud Drive</div><div class="side-item"><span>▰</span>Shared</div><h4>Tags</h4><div class="side-item"><span style="color:#f55">●</span>Red</div><div class="side-item"><span style="color:#6c6">●</span>Green</div></aside><main class="file-area"><h2>${section}</h2><div class="file-grid">${[['▰','Design'],['▰','Projects'],['▰','Travel'],['📄','Brief.pdf'],['🖼️','Tahoe.jpg'],['🎵','Dreams.m4a'],['📊','Research'],['📦','Archive.zip']].map(x=>`<div class="file"><div class="file-art">${x[0]}</div>${x[1]}</div>`).join('')}</div></main></div>`,{width:790,height:510,toolbar:'<button class="toolbutton">‹</button><button class="toolbutton">›</button><button class="toolbutton">⋯</button>'})}
function openSafari(){const win=windowHTML('safari','Safari',`<div class="browser-toolbar"><button>‹</button><button>›</button><div class="address-bar">🔒 start.tahoe</div><button>↗</button><button>＋</button></div><main class="browser-page"><span style="font-size:50px">🌐</span><h1>Good afternoon.</h1><div class="search-box">⌕ Search the web</div><div class="favorites">${[['◉','OpenAI'],['N','News'],['▶','Videos'],['☁','iCloud'],['＋','Add']].map(x=>`<div class="favorite"><span>${x[0]}</span><p>${x[1]}</p></div>`).join('')}</div></main>`,{width:850,height:540});$('.search-box',win).onclick=()=>showSpotlight();return win}
function openMessages(){const win=windowHTML('messages','Messages',`<div class="messages-layout"><aside class="list-pane"><input placeholder="Search" style="width:100%;padding:7px;border:0;border-radius:8px;margin-bottom:8px">${[['A','Alex','The Tahoe prototype…'],['M','Maya','See you soon!'],['T','Team','Jordan: approved ✓']].map((x,i)=>`<div class="conversation ${i?'':'active'}"><span class="avatar">${x[0]}</span><div><b>${x[1]}</b><small>${x[2]}</small></div></div>`).join('')}</aside><main class="chat"><div class="chat-head"><b>Alex</b><small style="display:block">iMessage</small></div><div class="bubbles"><div class="bubble">Hey! How is the Tahoe desktop coming along?</div><div class="bubble me">It’s live — with working apps, menus, and glass everywhere ✨</div><div class="bubble">The Tahoe prototype looks beautiful!</div></div><form class="composer"><input placeholder="iMessage"><button>↑</button></form></main></div>`,{width:720,height:510});$('.composer',win).onsubmit=e=>{e.preventDefault();const input=$('input',e.currentTarget);if(input.value.trim()){const b=document.createElement('div');b.className='bubble me';b.textContent=input.value;$('.bubbles',win).append(b);input.value=''}};return win}
function openMail(){return windowHTML('mail','Mail',`<div class="mail-layout"><aside class="list-pane"><b>Favorites</b>${['Inbox  4','VIP','Drafts','Sent','Junk','Bin'].map((x,i)=>`<div class="side-item ${i?'':'active'}">${x}</div>`).join('')}</aside><main style="padding:25px"><div style="color:#79818e">Apple Design Team &lt;design@example.com&gt;</div><h1>Welcome to Tahoe</h1><hr style="border:0;border-top:1px solid #ddd"><p>Hi there,</p><p>Thanks for trying this interactive web desktop. The new design brings translucent materials, softer shapes, and a renewed sense of depth to every window.</p><p>Try the menus, open apps from the Dock, search with Spotlight, and adjust controls in Control Center.</p><p>Enjoy exploring!</p></main></div>`,{width:760,height:500,toolbar:'<button class="toolbutton">✎</button><button class="toolbutton">↩</button>'})}
function openMaps(){return windowHTML('maps','Maps',`<div class="map-canvas"><div style="position:absolute;z-index:3;top:15px;left:15px;background:white;border-radius:10px;padding:10px 15px;box-shadow:0 3px 12px #aaa">⌕ Search Maps</div><span class="map-pin">●</span></div>`,{width:790,height:510})}
function openPhotos(){const colors=[['#3a84e8','#8be1ff'],['#fe8c67','#ffd6a5'],['#6b8f56','#d9ed92'],['#7251a8','#e79be9'],['#ed6677','#ffc58f'],['#246e91','#7bcbe0'],['#63814a','#bdcc86'],['#345477','#c5e6ed']];return windowHTML('photos','Photos',`<main class="photo-layout"><h1>Library</h1><p style="color:#757d88">August 2026</p><div class="photo-grid">${colors.map((c,i)=>`<div class="photo-tile" style="--a:${c[0]};--b:${c[1]}">${['🏔','🌊','🌿','🌸','🌅','⛵','🌲','❄'][i]}</div>`).join('')}</div></main>`,{width:760,height:500})}
function openFaceTime(){const win=windowHTML('facetime','FaceTime',`<div class="facetime-screen"><div><span class="avatar">A</span><h2>Alex</h2><p>Available for FaceTime</p><button class="call-button">▰</button></div></div>`,{width:660,height:460});$('.call-button',win).onclick=e=>{e.currentTarget.textContent=e.currentTarget.textContent==='▰'?'■':'▰';e.currentTarget.style.background=e.currentTarget.textContent==='■'?'#ff3b30':'#35c759';toast(e.currentTarget.textContent==='■'?'Calling Alex…':'Call ended')};return win}
function openCalendar(){const d=new Date(),first=new Date(d.getFullYear(),d.getMonth(),1).getDay(),days=new Date(d.getFullYear(),d.getMonth()+1,0).getDate();let cells='';for(let i=0;i<first;i++)cells+='<div></div>';for(let i=1;i<=days;i++)cells+=`<div class="${i===d.getDate()?'today':''}"><b>${i}</b>${i===d.getDate()?'<div class="event-pill">10:00 Design review</div>':''}</div>`;return windowHTML('calendar','Calendar',`<main class="calendar-month"><h1>${d.toLocaleDateString([],{month:'long',year:'numeric'})}</h1><div style="display:grid;grid-template-columns:repeat(7,1fr);text-align:center;color:#7d8590;font-size:11px;margin-bottom:6px">${['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(x=>`<span>${x}</span>`).join('')}</div><div class="calendar-grid">${cells}</div></main>`,{width:770,height:530})}
function openNotes(){return windowHTML('notes','Notes',`<div class="note-layout"><aside class="note-list"><b>Notes</b><div class="note-card active"><b>Ideas</b><small>Today · Tahoe interface</small></div><div class="note-card"><b>Trip packing</b><small>Yesterday · Camera, charger…</small></div><div class="note-card"><b>Books to read</b><small>Monday · The Creative Act…</small></div></aside><main class="note-editor"><input value="Ideas" aria-label="Note title"><textarea aria-label="Note body">Tahoe interface\n\n• Translucent glass surfaces\n• Soft, rounded windows\n• Interactive Control Center\n• Working Spotlight search\n• Draggable, resizable-feeling apps\n\nEverything is saved automatically while this window stays open.</textarea></main></div>`,{width:700,height:500,toolbar:'<button class="toolbutton">✎</button>'})}
function openMusic(){const win=windowHTML('music','Music',`<div class="music-layout"><aside class="sidebar"><h4>Apple Music</h4>${['Home','New','Radio'].map(x=>`<div class="side-item">♫ &nbsp;${x}</div>`).join('')}<h4>Library</h4>${['Recently Added','Artists','Albums','Songs'].map(x=>`<div class="side-item">${x}</div>`).join('')}</aside><main class="music-main"><div class="music-hero"><div><small>ESSENTIAL ALBUM</small><h1>Golden Hour</h1><p>Dreamlike classics for a clear day.</p></div></div><h2>Recently Played</h2>${['Dreams|Fleetwood Mac|4:17','Pink + White|Frank Ocean|3:04','Sunset Lover|Petit Biscuit|3:58'].map((x,i)=>{const p=x.split('|');return`<div class="track" data-song="${p[0]}"><span>${i+1}</span><span><b>${p[0]}</b><small style="display:block;color:#777">${p[1]}</small></span><span>${p[2]}</span></div>`}).join('')}</main></div>`,{width:790,height:520});$$('.track',win).forEach(t=>t.onclick=()=>{state.playing=true;$('#cc-song').textContent=t.dataset.song;$('#cc-play').textContent='❚❚';toast(`Playing ${t.dataset.song}`)});return win}
function openSettings(){const win=windowHTML('settings','System Settings',`<div class="settings-layout"><aside class="settings-list"><div class="settings-user"><span class="avatar">DU</span><span><b>Demo User</b><small style="display:block">Apple Account</small></span></div><input placeholder="Search" style="width:100%;padding:7px;border:0;border-radius:8px;margin-bottom:8px">${['Wi‑Fi','Bluetooth','Network','Notifications','Sound','Focus','Screen Time','General','Appearance'].map((x,i)=>`<div class="side-item ${i===8?'active':''}">${['⌁','ᛒ','◉','●','♫','☾','◷','⚙','◐'][i]} &nbsp; ${x}</div>`).join('')}</aside><main class="settings-content"><h1>Appearance</h1><div class="setting-row"><span>Appearance</span><span style="margin-left:auto">◻ Light &nbsp; ◧ Auto &nbsp; ◼ Dark</span></div><div class="setting-row"><span>Accent color</span><span style="margin-left:auto;color:#0a84ff">●</span></div><div class="setting-row"><span>Allow wallpaper tinting in windows</span><button class="switch on"></button></div><div class="setting-row"><span>Show scroll bars</span><span style="margin-left:auto;color:#707782">Automatically ▾</span></div></main></div>`,{width:750,height:520});$$('.switch',win).forEach(s=>s.onclick=()=>s.classList.toggle('on'));return win}
function openTrash(){return windowHTML('trash','Trash',`<div class="generic-empty"><div><span class="big-icon">♲</span><h2>Trash is Empty</h2><p style="color:#77808b">Items you move to the Trash will appear here.</p></div></div>`,{width:650,height:420})}
function openAbout(){windowHTML('about','About This Mac',`<div class="generic-empty"><div><div style="width:110px;height:110px;border-radius:25px;background:linear-gradient(135deg,#62c7ff,#4457ed);margin:auto;display:grid;place-items:center;color:white;font-size:55px">⌁</div><h1>macOS Tahoe</h1><p>Version 26.0 · Web Edition</p><p style="color:#76808b">Built as an interactive browser experience</p><button class="toolbutton" onclick="this.closest('.window').querySelector('p:last-of-type').textContent='Everything is up to date.'">Software Update…</button></div></div>`,{width:440,height:430})}
function openHelp(){windowHTML('help','Tahoe Help',`<main style="padding:35px"><h1>How can we help?</h1><div class="search-box">⌕ Search Tahoe Help</div><h3>Explore the desktop</h3><p>Open apps from the Dock, click the menu bar, drag windows by their title bars, or press <b>⌘ Space</b> to search.</p><h3>Quick controls</h3><p>Use Control Center to change brightness, sound, Wi‑Fi, Bluetooth, Focus, and Stage Manager.</p></main>`,{width:600,height:420})}
function addFolder(){let win=$('.window[data-app="finder"].focused');if(!win){openFinder();win=$('.window[data-app="finder"].focused')}const grid=$('.file-grid',win);if(grid){const f=document.createElement('div');f.className='file';f.innerHTML='<div class="file-art">▰</div>untitled folder';grid.prepend(f);toast('New folder created')}}

$$('[data-open]').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();openApp(b.dataset.open)}));
$('#control-button').onclick=e=>{e.stopPropagation();const c=$('#control-center'),show=c.classList.contains('hidden');closePanels('#control-center');c.classList.toggle('hidden',!show)};
$('#wifi-button').onclick=()=>{state.wifi=!state.wifi;toast(`Wi‑Fi ${state.wifi===false?'Off':'On'}`)};
$('#focus-button').onclick=e=>{e.currentTarget.classList.toggle('selected');toast(e.currentTarget.classList.contains('selected')?'Focus enabled':'Focus disabled')};
$('#clock-button').onclick=e=>{e.stopPropagation();const n=$('#notification-center'),show=n.classList.contains('hidden');closePanels('#notification-center');n.classList.toggle('hidden',!show)};
$('#clear-notifications').onclick=()=>{$$('.notification').forEach(n=>n.remove());toast('Notifications cleared')};
$$('[data-toggle]').forEach(t=>t.onclick=()=>{t.classList.toggle('on');const small=$('small',t);if(small)small.textContent=t.classList.contains('on')?'On':'Off'});
$('#stage-toggle').onclick=()=>{state.stage=!state.stage;desktop.classList.toggle('stage-mode',state.stage);toast(`Stage Manager ${state.stage?'On':'Off'}`)};
$('#brightness').oninput=e=>{state.brightness=e.target.value;desktop.style.filter=`brightness(${.55+e.target.value/180})`};
$('#volume').oninput=e=>state.volume=e.target.value;
$('#cc-play').onclick=e=>{state.playing=!state.playing;e.currentTarget.textContent=state.playing?'❚❚':'▶';toast(state.playing?'Now playing':'Paused')};
$('#cc-next').onclick=()=>{const songs=['Dreams','Pink + White','Sunset Lover'];let i=(songs.indexOf($('#cc-song').textContent)+1)%songs.length;$('#cc-song').textContent=songs[i];toast(`Playing ${songs[i]}`)};

function showSpotlight(){closePanels('#spotlight');const s=$('#spotlight');s.classList.remove('hidden');const input=$('#spotlight-input');input.value='';input.focus();renderSearch('')}
$('#spotlight-button').onclick=e=>{e.stopPropagation();showSpotlight()};
function renderSearch(q){const all=Object.entries(appMeta).filter(([id,m])=>m[0].toLowerCase().includes(q.toLowerCase())).slice(0,6);$('#spotlight-results').innerHTML=all.length?all.map(([id,m],i)=>`<div class="spotlight-result ${i?'':'selected'}" data-result="${id}"><span class="dock-icon ${id}">${m[1]}</span><span><b>${m[0]}</b><small style="display:block">Application</small></span></div>`).join(''):'<div class="spotlight-empty">No results found</div>'}
$('#spotlight-input').oninput=e=>renderSearch(e.target.value);$('#spotlight-results').onclick=e=>{const r=e.target.closest('[data-result]');if(r)openApp(r.dataset.result)};
document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.code==='Space'){e.preventDefault();showSpotlight()}if(e.key==='Escape')closePanels();if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='w'){const w=$('.window.focused');if(w)closeWindow(w)}if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='m'){const w=$('.window.focused');if(w)minimizeWindow(w)}});
document.addEventListener('click',e=>{if(!e.target.closest('.popover,.glass-panel,#notification-center,#spotlight,.menu-trigger,.status-button,.clock'))closePanels()});

function showLock(){const lock=document.createElement('div');lock.style.cssText='position:absolute;inset:0;z-index:5000;background:rgba(4,18,45,.42);backdrop-filter:blur(35px);display:grid;place-items:center;color:white;text-align:center';lock.innerHTML='<div><div class="avatar" style="width:90px;height:90px;font-size:25px;margin:auto">DU</div><h1>Demo User</h1><p>Click to unlock</p></div>';lock.onclick=()=>lock.remove();desktop.append(lock)}

setTimeout(()=>toast('Tip: Press ⌘ Space to search'),900);
